## Pocketing definitions

We are defining "pockets" as local clusters of disease.  These could be generated by underlying pockets (or more generally spatially autocorrelated) of disease predictors such as income, etc., but to start with we will just consider spatial variance in disease risk itself.

We will compute a pocketing component and add it to the linear predictor that we are constructing to include other factors (linear/quadratic trend, income effect, etc. etc.).  Basically, we need to 

* pick a number of pockets (specified exactly: could be given as a Poisson mean?)
* pick a set of center points (at random within the spatial domain: could be clustered or evenly spaced)
* decide on an 'influence function' or 'kernel' $K$, e.g. exponential ($K(r) = \exp(-r)$) or inverse-square ("gravity model", $1/r^2$) or Gaussian ($\exp(-r^2)$)
* decide on a scale parameter, i.e. scaling $r$: e.g. $K(r)= 1/(r/s)^2$
* pockets could have different scales/strengths, or they could be identical (start with indentical).  Exponential/Gaussian kernels can have both strength and scale parameters (e.g. $a \exp(-r/s)$); for power-law (e.g. gravity) kernels we can't distinguish between strength and scale (e.g. $a \cdot 1/(r/s)^2 = (as^2) 1/r^2$).
* sum pocketing effects from all pockets: compute the distances $r_i$ from each household to every pocket ($i$) and find $\sum K(r_i,a_i,s_i)$ (or more specifically $\sum K(r_i,a,s)$ for the typical case where the strength and scale of pocketing are the same for all pockets.
* scale this term as we do for all the other components of disease risk and add it to the linear predictor for disease risk.

